zdotdir="${ZDOTDIR:-$HOME}"

##### prezto #####
if [[ ! -d ${zdotdir}/.zprezto ]]; then
  git clone --recursive https://github.com/sorin-ionescu/prezto.git ${zdotdir}/.zprezto
  setopt EXTENDED_GLOB
  for rcfile in ${zdotdir}/.zprezto/runcoms/^README.md; do
    ln -s "$rcfile" "${zdotdir}/.${rcfile:t}"
  done
fi

[ -d ${zdotdir}/.zprezto ] && source ${zdotdir}/.zprezto/init.zsh && prompt steeef

##### antigen #####
[ ! -d ${zdotdir}/antigen ] && git clone git@github.com:zsh-users/antigen.git ${zdotdir}/antigen

if [[ -f ${zdotdir}/antigen/antigen.zsh ]]; then
  source ${zdotdir}/antigen/antigen.zsh
  antigen bundle mollifier/anyframe
  antigen bundle marzocchi/zsh-notify
  antigen apply
fi

##### cdr #####
autoload -Uz chpwd_recent_dirs cdr add-zsh-hook
add-zsh-hook chpwd chpwd_recent_dirs
zstyle ':chpwd:*' recent-dirs-max 500
zstyle ':chpwd:*' recent-dirs-pushd true

##### history #####
HISTFILE=${zdotdir}/.zsh_history
HISTSIZE=100000
SAVEHIST=100000
setopt hist_ignore_dups
setopt share_history

##### Read settings #####
[ -f ~/dotfiles/zsh/global              ] && source ~/dotfiles/zsh/global
[ -f ~/dotfiles/zsh/alias               ] && source ~/dotfiles/zsh/alias
[ -f ~/dotfiles/zsh/functions           ] && source ~/dotfiles/zsh/functions
[ -f ~/dotfiles/zsh/keybinds            ] && source ~/dotfiles/zsh/keybinds
[ -f ~/dotfiles/zsh/global_private      ] && source ~/dotfiles/zsh/global_private
